# Generated by Django 5.0.1 on 2024-02-15 13:59

import utils.snowflakes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflakes.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
