# Generated by Django 5.0.2 on 2024-02-22 14:47

import utils.snowflakes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohort_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflakes.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="internprofile",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflakes.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
