# Generated by Django 5.0.2 on 2024-02-21 13:31

import django.db.models.deletion
import utils.snowflakes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='id',
            field=models.BigIntegerField(default=utils.snowflakes.Snowflake.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interns', to='cohort_management.cohort'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='id',
            field=models.BigIntegerField(default=utils.snowflakes.Snowflake.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
