# Generated by Django 5.0.2 on 2024-02-19 22:38

import utils.snowflakes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_management', '0004_alter_cohort_id_alter_internprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='id',
            field=models.BigIntegerField(default=utils.snowflakes.Snowflake.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='id',
            field=models.BigIntegerField(default=utils.snowflakes.Snowflake.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='role',
            field=models.CharField(choices=[('Product designer', 'Product designer'), ('Backend developer', 'Backend developer'), ('Frontend developer', 'Frontend developer'), ('Product manager', 'Product manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
