# Generated by Django 5.0.1 on 2024-02-15 13:59

import django.db.models.deletion
import utils.snowflakes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TalentRequestTicket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=utils.snowflakes.Snowflake.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=50)),
                ("company_mail", models.EmailField(max_length=254)),
                ("company_address", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("talent_count", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DefermentTicket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=utils.snowflakes.Snowflake.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deferment_reason", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DECLINED", "Declined"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=utils.snowflakes.Snowflake.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                (
                    "recipient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentTicket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=utils.snowflakes.Snowflake.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_reason", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNSUCCESSFUL", "Unsuccessful"),
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                        ],
                        max_length=50,
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("account_owner", models.CharField(max_length=11)),
                ("account_bank", models.CharField(max_length=50)),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
